INSERT INTO PERSON (ID,NAME, LOCATION, BIRTH_DATE) VALUES (1, 'SATYANARAYANA CH', 'A VEMAVARAM', '1965-aug-26');
INSERT INTO PERSON (ID,NAME, LOCATION, BIRTH_DATE) VALUES (2, 'SATYAVATHI CH', 'A VEMAVARAM', '1975-jan-1');
INSERT INTO PERSON (ID,NAME, LOCATION, BIRTH_DATE) VALUES (3, 'MUKESH CH', 'A VEMAVARAM', '1995-sep-16');
INSERT INTO PERSON (ID,NAME, LOCATION, BIRTH_DATE) VALUES (4, 'KEDAR CH', 'A VEMAVARAM', '1999-aug-12');
INSERT INTO PERSON (ID,NAME, LOCATION, BIRTH_DATE) VALUES (5, 'PERSON CH', 'A VEMAVARAM', '1996-aug-13');
INSERT INTO PERSON (ID,NAME, LOCATION, BIRTH_DATE) VALUES (6, 'PERSON2 CH', 'A VEMAVARAM', '2000-sep-26');
